import { 
  ListingItem, 
  UserProfile, 
  NoticeItem, 
  CarpoolItem, 
  SafeZone, 
  ExchangeRequest, 
  ChatMessage 
} from './types';

export const CURRENT_USER: UserProfile = {
  id: 'usr_me_01',
  name: 'Alex Rivera',
  email: 'arivera@metro.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  college: 'Metropolitan Tech University',
  major: 'Computer Science & Data',
  year: 'Junior (Class of 2027)',
  bio: 'CS Junior passionate about AI, open source, and campus hackathons. Always open to lending gear or trading textbooks!',
  isVerified: true,
  rating: 4.9,
  savedListingIds: ['res_02', 'opp_01', 'srv_gd_01'],
  completedExchanges: 14,
  campusCashBalance: 75.00,
};

export const COLLEGES = [
  'All Campuses',
  'Metropolitan Tech University',
  'Bay State University',
  'Pacific Coast College',
  'Apex Institute of Science',
];

export const SAFE_ZONES: SafeZone[] = [
  {
    id: 'sz_01',
    name: 'Science Library Main Lobby',
    location: 'Building B, Ground Floor (Adjacent to Circulation Desk)',
    hours: 'Open 24/7 with Student Card Access',
    securityFeatures: ['Security Desk Staffed 24/7', 'High-Res CCTV Coverage', 'Well-Lit Exchange Tables', 'Emergency Blue Light Station'],
    description: 'The primary designated campus safe exchange hub with high foot traffic and campus security presence.',
    latRatio: 35,
    lngRatio: 42,
  },
  {
    id: 'sz_02',
    name: 'Student Union Atrium & Cafe',
    location: 'Student Activity Center, 1st Floor',
    hours: '7:00 AM – 11:00 PM Daily',
    securityFeatures: ['Campus Police Foot Patrol', 'Public Seating & Power Outlets', 'Staffed Information Kiosk'],
    description: 'Great central location for daytime book swaps, peer tutoring meetups, and design reviews over coffee.',
    latRatio: 58,
    lngRatio: 55,
  },
  {
    id: 'sz_03',
    name: 'Campus Police Safe Exchange Bay',
    location: 'Public Safety Building (West Parking Lot 3)',
    hours: '24/7 Monitored Safe Zone',
    securityFeatures: ['Direct Police Station Proximity', '24/7 Video Recording', 'Emergency Call Box'],
    description: 'Recommended for high-value electronic exchanges (laptops, cameras, tablets, gaming consoles).',
    latRatio: 80,
    lngRatio: 25,
  },
  {
    id: 'sz_04',
    name: 'Engineering & Maker Innovation Hall',
    location: 'Engineering Plaza - Room 102 High Bay',
    hours: '8:00 AM – 10:00 PM',
    securityFeatures: ['Keycard Access Only', 'Lab Staff on Duty', 'CCTV'],
    description: 'Ideal spot for project collaboration handoffs, 3D print gear, and robotics hardware sharing.',
    latRatio: 25,
    lngRatio: 78,
  }
];

export const INITIAL_NOTICES: NoticeItem[] = [
  {
    id: 'not_01',
    type: 'lost',
    itemCategory: 'id_card',
    title: 'Lost Student ID Card: Alex Rivera (#902384)',
    description: 'Misplaced my university ID card with red lanyard. Likely dropped between the Science Library and West Dining Hall yesterday afternoon around 4 PM.',
    locationFoundOrLost: 'Between Science Library & Dining Hall',
    college: 'Metropolitan Tech University',
    dateReported: 'Today at 9:15 AM',
    contactName: 'Alex Rivera',
    contactEmail: 'arivera@metro.edu',
    isClaimed: false,
    reward: 'Free Coffee / $10 Campus Cash',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'not_02',
    type: 'found',
    itemCategory: 'notebook',
    title: 'Found Black Moleskine Organic Chemistry Notebook',
    description: 'Found a black hardcover spiral notebook filled with detailed CHEM 220 reaction diagrams and handwritten notes on the 2nd floor study carrels.',
    locationFoundOrLost: 'Library 2nd Floor (Table 14)',
    college: 'Metropolitan Tech University',
    dateReported: 'Yesterday at 5:30 PM',
    contactName: 'Sarah Jenkins',
    contactEmail: 'sjenkins@metro.edu',
    isClaimed: false,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'not_03',
    type: 'lost',
    itemCategory: 'tech',
    title: 'Lost AirPods Pro (2nd Gen) in Matte Black Case',
    description: 'Left my AirPods case in the Engineering Computer Lab 304 after the 2 PM algorithms lecture. Has a tiny blue astronaut sticker on it.',
    locationFoundOrLost: 'Engineering Lab 304',
    college: 'Metropolitan Tech University',
    dateReported: '2 days ago',
    contactName: 'Tyler Wong',
    contactEmail: 'twong@metro.edu',
    isClaimed: false,
    reward: '$25 Campus Cash',
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'not_04',
    type: 'found',
    itemCategory: 'keys',
    title: 'Found Dorm Room Keys with Yellow Swiss Army Keychain',
    description: 'Found a set of 3 dorm keys and a mail key on the grass near North Quad benches. Handed to Student Center Front Desk for safekeeping.',
    locationFoundOrLost: 'Student Center Front Desk',
    college: 'Metropolitan Tech University',
    dateReported: '3 days ago',
    contactName: 'Front Desk Officer',
    contactEmail: 'support@metro.edu',
    isClaimed: true,
    claimedBy: 'Jordan Hayes',
    image: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_CARPOOLS: CarpoolItem[] = [
  {
    id: 'cp_01',
    driverName: 'Liam Sterling',
    driverAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    college: 'Metropolitan Tech University',
    origin: 'Campus North Dorms',
    destination: 'Downtown Tech District & Train Station',
    departureTime: 'Friday at 4:30 PM',
    seatsTotal: 4,
    seatsAvailable: 2,
    pricePerSeat: 5,
    carModel: 'Honda Civic (Spacious trunk for luggage)',
    notes: 'Heading home for the weekend! Can drop off along Route 9 or at the Central Amtrak terminal.',
  },
  {
    id: 'cp_02',
    driverName: 'Samantha Wu',
    driverAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    college: 'Metropolitan Tech University',
    origin: 'West Campus Student Parking',
    destination: 'Regional Hackathon Venue (Metro Arena)',
    departureTime: 'Saturday at 7:45 AM',
    seatsTotal: 3,
    seatsAvailable: 3,
    pricePerSeat: 0,
    carModel: 'Toyota RAV4 Hybrid',
    notes: 'Free ride for HackMetro attendees! Playing upbeat coding synthwave music.',
  },
];

export const INITIAL_LISTINGS: ListingItem[] = [
  // --- RESOURCES ---
  {
    id: 'res_01',
    pillar: 'resource',
    title: 'TI-84 Plus CE Color Graphing Calculator',
    description: 'Barely used for one semester of Multivariable Calculus. Includes charging cable, protective slide cover, and preloaded math programs. Perfect for Calc, Stats, or Physics.',
    category: 'electronics',
    pricingType: 'fixed',
    price: 45,
    condition: 'like_new',
    courseCode: 'MATH 200',
    location: 'Science Library or West Hall',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['calculator', 'math', 'electronics', 'essentials'],
    author: {
      id: 'usr_02',
      name: 'Maya Chen',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      email: 'mchen@metro.edu',
      major: 'Electrical Engineering',
      year: 'Senior',
      college: 'Metropolitan Tech University',
      rating: 5.0,
      reviewCount: 19,
      isVerified: true,
      badge: 'Top Seller',
    },
    createdAt: '2 hours ago',
    status: 'active',
    likesCount: 12,
    urgency: 'regular',
  },
  {
    id: 'res_notes_01',
    pillar: 'resource',
    title: 'CS 106B Complete Data Structures & C++ Final Exam Cheat Sheet',
    description: 'High-yield 18-page comprehensive study notes covering Big-O, Pointer memory diagrams, Tree traversals, Graph BFS/DFS, Heaps, and dynamic programming templates. Verified A+ grade.',
    category: 'study_notes',
    pricingType: 'free',
    price: 0,
    condition: 'brand_new',
    courseCode: 'CS 106B',
    location: 'Instant Digital PDF Download',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['notes', 'cs106b', 'c++', 'algorithms', 'pdf', 'cheat-sheet'],
    documentInfo: {
      title: 'CS 106B Comprehensive Midterm & Final Study Guide',
      pages: 18,
      fileSize: '3.4 MB',
      previewUrl: 'https://example.com/cs106b-notes.pdf',
      previewSnippets: [
        'Chapter 1: Memory Layout & Pointer Arithmetic (Stack vs Heap, Dangling Pointers)',
        'Chapter 2: Abstract Data Types (Vector, Grid, Stack, Queue, Map, Set)',
        'Chapter 3: Recursive Backtracking & Sudoku/Maze Solving Algorithmic Patterns',
        'Chapter 4: Binary Search Trees & AVL Balance Rotations (Single/Double Rotations)',
        'Chapter 5: Graph Algorithms (Dijkstra vs A*, Minimum Spanning Tree Prim/Kruskal)',
      ],
    },
    author: {
      id: 'usr_07',
      name: 'David Kim',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      email: 'dkim@metro.edu',
      major: 'Computer Science',
      year: 'Senior',
      college: 'Metropolitan Tech University',
      rating: 5.0,
      reviewCount: 34,
      isVerified: true,
      badge: 'Certified TA',
    },
    createdAt: '4 hours ago',
    status: 'active',
    likesCount: 52,
    urgency: 'regular',
  },
  {
    id: 'res_02',
    pillar: 'resource',
    title: 'Organic Chemistry Structure & Function (8th Ed) + Model Kit',
    description: 'Complete textbook with molecular model kit (all atoms & bonds accounted for). No highlighted pages. Saved me in CHEM 220!',
    category: 'textbooks',
    pricingType: 'fixed',
    price: 35,
    condition: 'good',
    courseCode: 'CHEM 220',
    location: 'Chemistry Plaza / North Quad',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['textbook', 'chemistry', 'model-kit', 'pre-med'],
    author: {
      id: 'usr_03',
      name: 'Jordan Hayes',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      email: 'jhayes@metro.edu',
      major: 'Biochemistry',
      year: 'Junior',
      college: 'Metropolitan Tech University',
      rating: 4.8,
      reviewCount: 8,
      isVerified: true,
    },
    createdAt: '5 hours ago',
    status: 'active',
    likesCount: 7,
    urgency: 'urgent',
  },
  {
    id: 'res_04',
    pillar: 'resource',
    title: 'Free Biology 101 Lab Coat (Size M) + Safety Goggles',
    description: 'Donating my lab coat and ANSI-approved safety goggles to any incoming freshman taking General Bio/Chem. Passing it forward for free!',
    category: 'lab_gear',
    pricingType: 'free',
    price: 0,
    condition: 'good',
    courseCode: 'BIO 101',
    location: 'Student Life Center Desk',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['free', 'donation', 'lab-coat', 'safety', 'bio'],
    author: {
      id: 'usr_05',
      name: 'Samantha Wu',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      email: 'swu@metro.edu',
      major: 'Biology',
      year: 'Sophomore',
      college: 'Metropolitan Tech University',
      rating: 5.0,
      reviewCount: 6,
      isVerified: true,
      badge: 'Campus Giver',
    },
    createdAt: '3 hours ago',
    status: 'active',
    likesCount: 31,
    urgency: 'urgent',
  },

  // --- EXPANDED STUDENT SERVICES ---
  {
    id: 'srv_gd_01',
    pillar: 'service',
    title: 'Club Logos, UI/UX Prototyping & Event Poster Graphic Design',
    description: 'Design major with 3+ years in Figma and Illustrator. I design eye-catching posters for student clubs, Instagram flyers, merch/t-shirts, and Figma UI prototypes for student tech projects.',
    category: 'graphic_design',
    pricingType: 'fixed',
    price: 25,
    location: 'Online Delivery / Figma Files',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['design', 'figma', 'branding', 'posters', 'ui-ux', 'flyers'],
    serviceSkills: ['Figma Prototyping', 'Adobe Illustrator', 'Logo Design', 'Print Posters', 'Social Media Graphics'],
    author: {
      id: 'usr_gd_01',
      name: 'Serena Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      email: 'svance@metro.edu',
      major: 'Interaction & Graphic Design',
      year: 'Senior',
      college: 'Metropolitan Tech University',
      rating: 5.0,
      reviewCount: 27,
      isVerified: true,
      badge: 'Design Lead',
    },
    createdAt: '2 hours ago',
    status: 'active',
    likesCount: 36,
  },
  {
    id: 'srv_vid_01',
    pillar: 'service',
    title: 'TikTok/Reels, YouTube Recaps & Event Video Editing (Premiere/DaVinci)',
    description: 'Fast turnaround video editing with motion graphics, captions, sound design, and color grading. Perfect for campus organizations, student startups, or personal vlogs.',
    category: 'video_editing',
    pricingType: 'hourly',
    price: 20,
    location: 'Online / Google Drive Handoff',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['video', 'editing', 'premiere', 'davinci', 'reels', 'tiktok'],
    serviceSkills: ['Premiere Pro', 'DaVinci Resolve', 'Dynamic Captions', 'Color Grading', 'Sound Mixing'],
    author: {
      id: 'usr_vid_01',
      name: 'Julian Ross',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      email: 'jross@metro.edu',
      major: 'Film & Media Production',
      year: 'Junior',
      college: 'Metropolitan Tech University',
      rating: 4.9,
      reviewCount: 16,
      isVerified: true,
    },
    createdAt: '4 hours ago',
    status: 'active',
    likesCount: 22,
  },
  {
    id: 'srv_02',
    pillar: 'service',
    title: 'Graduation, Club Headshots & LinkedIn Portrait Photography',
    description: 'Sony A7IV photographer offering 30-min campus portrait sessions (Quad, Arch, Fountain). Includes 8 edited high-res photos. Great for grad invites and resume updates.',
    category: 'photography',
    pricingType: 'fixed',
    price: 35,
    location: 'Campus Quad & Memorial Bell Tower',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['photography', 'headshots', 'graduation', 'linkedin', 'portraits'],
    author: {
      id: 'usr_08',
      name: 'Chloe Laurent',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      email: 'claurent@metro.edu',
      major: 'Digital Media Arts',
      year: 'Senior',
      college: 'Metropolitan Tech University',
      rating: 4.9,
      reviewCount: 28,
      isVerified: true,
      badge: 'Top Creator',
    },
    createdAt: '6 hours ago',
    status: 'active',
    likesCount: 19,
  },
  {
    id: 'srv_04',
    pillar: 'service',
    title: 'Tech & Business Resume Review + Mock Interview Practice',
    description: 'Incoming SWE intern at top tech. I will thoroughly review your tech resume with line-by-line ATS feedback and run a 45-min mock interview with personalized scorecards.',
    category: 'resume_review',
    pricingType: 'hourly',
    price: 15,
    location: 'Google Meet / Online',
    college: 'Bay State University',
    images: [
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['internships', 'resume', 'career', 'mock-interview', 'tech'],
    author: {
      id: 'usr_10',
      name: 'Ananya Sharma',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      email: 'asharma@baystate.edu',
      major: 'Computer Science',
      year: 'Senior',
      college: 'Bay State University',
      rating: 5.0,
      reviewCount: 41,
      isVerified: true,
      badge: 'Career Mentor',
    },
    createdAt: '8 hours ago',
    status: 'active',
    likesCount: 38,
  },
  {
    id: 'srv_lang_01',
    pillar: 'service',
    title: 'Spanish & French Conversational Practice / Grammar Tutoring',
    description: 'Native Spanish speaker and French B2 certified. Offering fun, conversational practice sessions, essay proofreading, and vocabulary prep for study abroad or language classes.',
    category: 'language_exchange',
    pricingType: 'hourly',
    price: 12,
    location: 'Campus Cafe or Zoom',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['languages', 'spanish', 'french', 'tutoring', 'conversation'],
    serviceSkills: ['Conversational Fluency', 'Essay Proofreading', 'Grammar Drill', 'Study Abroad Prep'],
    author: {
      id: 'usr_lang_01',
      name: 'Mateo Ortiz',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      email: 'mortiz@metro.edu',
      major: 'International Relations',
      year: 'Junior',
      college: 'Metropolitan Tech University',
      rating: 5.0,
      reviewCount: 15,
      isVerified: true,
    },
    createdAt: '1 day ago',
    status: 'active',
    likesCount: 20,
  },
  {
    id: 'srv_evt_01',
    pillar: 'service',
    title: 'Campus Event Audio/Visual Setup & Live Stage Assistance',
    description: 'Experienced live sound engineer & AV technician. Available for student club festivals, talent shows, hackathon setups, microphones, speakers, and live stream rigs.',
    category: 'event_assistance',
    pricingType: 'hourly',
    price: 18,
    location: 'Any Campus Auditorium / Hall',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['audio', 'sound', 'events', 'av-setup', 'lighting', 'festivals'],
    serviceSkills: ['Soundboard Mixing', 'PA System Setup', 'OBS Livestreaming', 'Stage Management'],
    author: {
      id: 'usr_evt_01',
      name: 'Kai Takahashi',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      email: 'ktakahashi@metro.edu',
      major: 'Music Tech & Audio Eng',
      year: 'Senior',
      college: 'Metropolitan Tech University',
      rating: 4.9,
      reviewCount: 21,
      isVerified: true,
      badge: 'Event Veteran',
    },
    createdAt: '1 day ago',
    status: 'active',
    likesCount: 27,
  },

  // --- PROJECT COLLABORATION & OPPORTUNITIES ---
  {
    id: 'opp_collab_01',
    pillar: 'opportunity',
    title: 'Co-Founders & Mobile Dev for "CampusBite" Student Food Surplus App',
    description: 'We are building an iOS/Android app to connect student dining surplus with local college food pantries. We have seed interest from the University Sustainability Fund. Looking for React Native/Flutter dev and Growth lead.',
    category: 'project_collab',
    pricingType: 'free',
    price: 0,
    timeCommitment: '6-8 hrs/week',
    deadline: 'Oct 25, 2026',
    location: 'Student Incubator & Discord',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['startup', 'react-native', 'mobile', 'sustainability', 'equity'],
    collaborationRoles: ['Mobile App Developer (React Native/Flutter)', 'Growth & Community Manager', 'UI/UX Designer'],
    author: {
      id: 'usr_collab_01',
      name: 'Nadia Patel',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      email: 'npatel@metro.edu',
      major: 'Computer Science & Entrepreneurship',
      year: 'Junior',
      college: 'Metropolitan Tech University',
      rating: 5.0,
      reviewCount: 11,
      isVerified: true,
      badge: 'Incubator Fellow',
    },
    createdAt: '1 hour ago',
    status: 'active',
    likesCount: 48,
    urgency: 'urgent',
  },
  {
    id: 'opp_01',
    pillar: 'opportunity',
    title: 'Seeking Frontend & UI Dev for Fall Hackathon Team (Prize $10k)',
    description: 'We are 2 backend/ML students building an AI-assisted campus mental wellness companion for the upcoming HackMetro 2026. Looking for 1 frontend wizard skilled in React/Next.js/Tailwind.',
    category: 'hackathon',
    pricingType: 'free',
    price: 0,
    timeCommitment: 'Weekend Sprint (36 hrs)',
    deadline: 'Friday, Oct 12',
    location: 'Student Innovation Center / Hybrid',
    college: 'Metropolitan Tech University',
    images: [
      'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['hackathon', 'react', 'frontend', 'ai', 'team-building'],
    author: {
      id: 'usr_11',
      name: 'Liam Sterling',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      email: 'lsterling@metro.edu',
      major: 'Artificial Intelligence',
      year: 'Junior',
      college: 'Metropolitan Tech University',
      rating: 4.9,
      reviewCount: 9,
      isVerified: true,
      badge: 'Hackathon Winner',
    },
    createdAt: '3 hours ago',
    status: 'active',
    likesCount: 29,
    urgency: 'urgent',
  },
  {
    id: 'opp_03',
    pillar: 'opportunity',
    title: 'Undergraduate Research Assistant: Autonomous Campus Robotics Lab',
    description: 'Prof. Garcia’s Robotics Lab is looking for 2 enthusiastic undergraduate research assistants to assist with LiDAR sensor calibration and computer vision testing. Academic credit or stipend available.',
    category: 'research',
    pricingType: 'hourly',
    price: 18,
    timeCommitment: '6-8 hrs / week',
    deadline: 'Next Monday',
    location: 'Robotics Wing - Room 104',
    college: 'Apex Institute of Science',
    images: [
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    ],
    tags: ['research', 'robotics', 'paid-position', 'computer-vision', 'ros'],
    author: {
      id: 'usr_13',
      name: 'Julian Vance (Lab Lead)',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      email: 'lab-garcia@apexinstitute.edu',
      major: 'Robotics Engineering',
      year: 'Graduate Researcher',
      college: 'Apex Institute of Science',
      rating: 5.0,
      reviewCount: 14,
      isVerified: true,
      badge: 'Faculty Lab',
    },
    createdAt: '1 day ago',
    status: 'active',
    likesCount: 45,
  }
];

export const INITIAL_REQUESTS: ExchangeRequest[] = [
  {
    id: 'req_01',
    listingId: 'res_01',
    listingTitle: 'TI-84 Plus CE Color Graphing Calculator',
    listingPillar: 'resource',
    listingImage: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=400&auto=format&fit=crop&q=80',
    senderId: 'usr_me_01',
    senderName: 'Alex Rivera',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    senderCollege: 'Metropolitan Tech University',
    receiverId: 'usr_02',
    status: 'accepted',
    message: 'Hey Maya! I\'m taking MATH 200 this term and would love to buy this. Can we meet at the Science Library tomorrow afternoon?',
    proposedDate: 'Tomorrow at 2:30 PM',
    proposedLocation: 'Science Library Lobby',
    createdAt: 'Yesterday',
  },
  {
    id: 'req_02',
    listingId: 'srv_gd_01',
    listingTitle: 'Club Logos & Figma UI Prototyping',
    listingPillar: 'service',
    listingImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&auto=format&fit=crop&q=80',
    senderId: 'usr_me_01',
    senderName: 'Alex Rivera',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    senderCollege: 'Metropolitan Tech University',
    receiverId: 'usr_gd_01',
    status: 'pending',
    message: 'Hi Serena! Our hackathon team is building a mental wellness app and would love your help designing 4 mobile screen mockups in Figma.',
    proposedDate: 'This Thursday at 4 PM',
    proposedLocation: 'Online / Figma Link',
    createdAt: '2 hours ago',
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_01',
    requestId: 'req_01',
    senderId: 'usr_me_01',
    senderName: 'Alex Rivera',
    text: 'Hey Maya! I\'m taking MATH 200 this term and would love to buy this. Can we meet at the Science Library tomorrow afternoon?',
    timestamp: 'Yesterday at 3:15 PM',
  },
  {
    id: 'msg_02',
    requestId: 'req_01',
    senderId: 'usr_02',
    senderName: 'Maya Chen',
    text: 'Sounds great Alex! 2:30 PM at the Science Library lobby works perfectly. I\'ll bring the charging cable and case.',
    timestamp: 'Yesterday at 3:42 PM',
  },
  {
    id: 'msg_03',
    requestId: 'req_01',
    senderId: 'system',
    senderName: 'Campus Security Tip',
    text: '🛡️ Safety Reminder: Science Library is an authorized Campus Safe Exchange Zone with staff present.',
    timestamp: 'Yesterday at 3:42 PM',
    isSystem: true,
  },
  {
    id: 'msg_04',
    requestId: 'req_02',
    senderId: 'usr_me_01',
    senderName: 'Alex Rivera',
    text: 'Hi Serena! Our hackathon team is building a mental wellness app and would love your help designing 4 mobile screen mockups in Figma.',
    timestamp: 'Today at 10:15 AM',
  }
];
